DOMAIN = "ai_home_copilot"
INTEGRATION_UNIQUE_ID = "pilotsuite_styx"
MAIN_DEVICE_IDENTIFIER = "styx_hub"
LEGACY_MAIN_DEVICE_IDENTIFIERS = (
    "ai_home_copilot",
    "copilot_hub",
    "pilotsuite_hub",
)

# Dashboard file layout:
# - primary branded path for new installs
# - legacy ai_home_copilot path kept for backwards compatibility
PRIMARY_DASHBOARD_DIR = "pilotsuite-styx"
LEGACY_DASHBOARD_DIR = DOMAIN

# Internal hass.data keys (namespaced to avoid entry_id collisions).
DATA_CORE = "_core"
DATA_RUNTIME = "runtime"

# Dispatcher signals
SIGNAL_CONTEXT_ENTITIES_REFRESH = f"{DOMAIN}_context_entities_refresh"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_TOKEN = "token"
CONF_TEST_LIGHT = "test_light_entity_id"
CONF_WEBHOOK_ID = "webhook_id"
CONF_WEBHOOK_URL = "webhook_url"
CONF_WATCHDOG_ENABLED = "watchdog_enabled"
CONF_WATCHDOG_INTERVAL_SECONDS = "watchdog_interval_seconds"
CONF_ENABLE_USER_PREFERENCES = "enable_user_preferences"

# MediaContext (read-only signals)
CONF_MEDIA_MUSIC_PLAYERS = "media_music_players"
CONF_MEDIA_TV_PLAYERS = "media_tv_players"

# MediaContext v2 (zone mapping + volume control)
CONF_MEDIA_CONTEXT_V2_ENABLED = "media_context_v2_enabled"

# Dev/Debug: push sanitized HA log snippets to Copilot-Core (opt-in).
CONF_DEVLOG_PUSH_ENABLED = "devlog_push_enabled"

# Core API v1: capabilities ping + HA->Core event forwarder (opt-in).
CONF_EVENTS_FORWARDER_ENABLED = "events_forwarder_enabled"
CONF_EVENTS_FORWARDER_FLUSH_INTERVAL_SECONDS = "events_forwarder_flush_interval_seconds"
CONF_EVENTS_FORWARDER_MAX_BATCH = "events_forwarder_max_batch"
CONF_EVENTS_FORWARDER_FORWARD_CALL_SERVICE = "events_forwarder_forward_call_service"
CONF_EVENTS_FORWARDER_IDEMPOTENCY_TTL_SECONDS = "events_forwarder_idempotency_ttl_seconds"

# Core API v1: events forwarder persistent queue (optional).
CONF_EVENTS_FORWARDER_PERSISTENT_QUEUE_ENABLED = "events_forwarder_persistent_queue_enabled"
CONF_EVENTS_FORWARDER_PERSISTENT_QUEUE_MAX_SIZE = "events_forwarder_persistent_queue_max_size"
CONF_EVENTS_FORWARDER_PERSISTENT_QUEUE_FLUSH_INTERVAL_SECONDS = (
    "events_forwarder_persistent_queue_flush_interval_seconds"
)

# Core API v1: events forwarder entity allowlist
CONF_EVENTS_FORWARDER_INCLUDE_HABITUS_ZONES = "events_forwarder_include_habitus_zones"
CONF_EVENTS_FORWARDER_INCLUDE_MEDIA_PLAYERS = "events_forwarder_include_media_players"
CONF_EVENTS_FORWARDER_ADDITIONAL_ENTITIES = "events_forwarder_additional_entities"

# HA log digest (local): surface relevant errors/warnings in HA (opt-in).
CONF_HA_ERRORS_DIGEST_ENABLED = "ha_errors_digest_enabled"

# Debug Level: off, light (errors only), full (all logs)
CONF_DEBUG_LEVEL = "debug_level"
DEBUG_LEVEL_OFF = "off"
DEBUG_LEVEL_LIGHT = "light"
DEBUG_LEVEL_FULL = "full"
DEBUG_LEVELS = [DEBUG_LEVEL_OFF, DEBUG_LEVEL_LIGHT, DEBUG_LEVEL_FULL]

# PilotSuite / Dashboard UX
CONF_PILOTSUITE_SHOW_SAFETY_BACKUP_BUTTONS = "pilotsuite_show_safety_backup_buttons"
CONF_PILOTSUITE_SHOW_DEV_SURFACE_BUTTONS = "pilotsuite_show_dev_surface_buttons"
CONF_PILOTSUITE_SHOW_GRAPH_BRIDGE_BUTTONS = "pilotsuite_show_graph_bridge_buttons"
CONF_HA_ERRORS_DIGEST_INTERVAL_SECONDS = "ha_errors_digest_interval_seconds"
CONF_HA_ERRORS_DIGEST_MAX_LINES = "ha_errors_digest_max_lines"
CONF_DEVLOG_PUSH_INTERVAL_SECONDS = "devlog_push_interval_seconds"
CONF_DEVLOG_PUSH_PATH = "devlog_push_path"
CONF_DEVLOG_PUSH_MAX_LINES = "devlog_push_max_lines"
CONF_DEVLOG_PUSH_MAX_CHARS = "devlog_push_max_chars"

# Optional: entities that emit LLM-generated suggestions we want to treat as "seed" candidates.
# Example: sensor.ai_automation_suggestions_openai
CONF_SUGGESTION_SEED_ENTITIES = "suggestion_seed_entities"
CONF_SEED_ALLOWED_DOMAINS = "seed_allowed_domains"
CONF_SEED_BLOCKED_DOMAINS = "seed_blocked_domains"
CONF_SEED_MAX_OFFERS_PER_HOUR = "seed_max_offers_per_hour"
CONF_SEED_MIN_SECONDS_BETWEEN_OFFERS = "seed_min_seconds_between_offers"
CONF_SEED_MAX_OFFERS_PER_UPDATE = "seed_max_offers_per_update"

# Privacy-first defaults: no personal IPs/entities shipped.
# Tip: set this to your HA host IP (LAN) or a resolvable hostname.
DEFAULT_HOST = "homeassistant.local"
DEFAULT_PORT = 8909
DEFAULT_TEST_LIGHT = ""
DEFAULT_WATCHDOG_ENABLED = False
DEFAULT_WATCHDOG_INTERVAL_SECONDS = 1800
DEFAULT_ENABLE_USER_PREFERENCES = True

DEFAULT_MEDIA_MUSIC_PLAYERS: list[str] = []
DEFAULT_MEDIA_TV_PLAYERS: list[str] = []

DEFAULT_DEVLOG_PUSH_ENABLED = False
DEFAULT_DEVLOG_PUSH_INTERVAL_SECONDS = 60
DEFAULT_DEVLOG_PUSH_PATH = "/api/v1/dev/logs"
DEFAULT_DEVLOG_PUSH_MAX_LINES = 220
DEFAULT_DEVLOG_PUSH_MAX_CHARS = 6000

DEFAULT_EVENTS_FORWARDER_ENABLED = False
DEFAULT_EVENTS_FORWARDER_FLUSH_INTERVAL_SECONDS = 5
DEFAULT_EVENTS_FORWARDER_MAX_BATCH = 50
DEFAULT_EVENTS_FORWARDER_FORWARD_CALL_SERVICE = False
DEFAULT_EVENTS_FORWARDER_IDEMPOTENCY_TTL_SECONDS = 300

DEFAULT_EVENTS_FORWARDER_PERSISTENT_QUEUE_ENABLED = False
DEFAULT_EVENTS_FORWARDER_PERSISTENT_QUEUE_MAX_SIZE = 500
DEFAULT_EVENTS_FORWARDER_PERSISTENT_QUEUE_FLUSH_INTERVAL_SECONDS = 5

DEFAULT_EVENTS_FORWARDER_INCLUDE_HABITUS_ZONES = True
DEFAULT_EVENTS_FORWARDER_INCLUDE_MEDIA_PLAYERS = True
DEFAULT_EVENTS_FORWARDER_ADDITIONAL_ENTITIES: list[str] = []

DEFAULT_HA_ERRORS_DIGEST_ENABLED = False
DEFAULT_DEBUG_LEVEL = DEBUG_LEVEL_OFF

DEFAULT_PILOTSUITE_SHOW_SAFETY_BACKUP_BUTTONS = False
DEFAULT_PILOTSUITE_SHOW_DEV_SURFACE_BUTTONS = False
DEFAULT_PILOTSUITE_SHOW_GRAPH_BRIDGE_BUTTONS = False
DEFAULT_HA_ERRORS_DIGEST_INTERVAL_SECONDS = 300
DEFAULT_HA_ERRORS_DIGEST_MAX_LINES = 800

DEFAULT_SUGGESTION_SEED_ENTITIES: list[str] = []
DEFAULT_SEED_ALLOWED_DOMAINS: list[str] = []
DEFAULT_SEED_BLOCKED_DOMAINS: list[str] = []
DEFAULT_SEED_MAX_OFFERS_PER_HOUR = 10
DEFAULT_SEED_MIN_SECONDS_BETWEEN_OFFERS = 30
DEFAULT_SEED_MAX_OFFERS_PER_UPDATE = 3

# Ollama LLM service (forwarded to Core add-on)
CONF_OLLAMA_HOST = "ollama_host"
CONF_OLLAMA_PORT = "ollama_port"
DEFAULT_OLLAMA_HOST = "localhost"
DEFAULT_OLLAMA_PORT = 11435

# SearXNG web search (forwarded to Core add-on)
CONF_SEARXNG_ENABLED = "searxng_enabled"
CONF_SEARXNG_HOST = "searxng_host"
CONF_SEARXNG_PORT = "searxng_port"
DEFAULT_SEARXNG_ENABLED = False
DEFAULT_SEARXNG_HOST = ""
DEFAULT_SEARXNG_PORT = 4041

HEADER_AUTH = "X-Auth-Token"

# User Preference Module (Multi-user learning)
CONF_USER_PREFERENCE_ENABLED = "user_preference_enabled"
CONF_TRACKED_USERS = "tracked_users"
CONF_PRIMARY_USER = "primary_user"
CONF_USER_LEARNING_MODE = "user_learning_mode"

USER_LEARNING_MODE_OFF = "off"
USER_LEARNING_MODE_PASSIVE = "passive"
USER_LEARNING_MODE_ACTIVE = "active"
USER_LEARNING_MODES = [USER_LEARNING_MODE_OFF, USER_LEARNING_MODE_PASSIVE, USER_LEARNING_MODE_ACTIVE]

DEFAULT_USER_PREFERENCE_ENABLED = False
DEFAULT_TRACKED_USERS: list[str] = []
DEFAULT_PRIMARY_USER = None
DEFAULT_USER_LEARNING_MODE = USER_LEARNING_MODE_PASSIVE

# Multi-User Preference Learning (MUPL) Module
CONF_MUPL_ENABLED = "mupl_enabled"
CONF_MUPL_PRIVACY_MODE = "mupl_privacy_mode"
CONF_MUPL_MIN_INTERACTIONS = "mupl_min_interactions"
CONF_MUPL_RETENTION_DAYS = "mupl_retention_days"

MUPL_PRIVACY_MODE_OPT_IN = "opt-in"
MUPL_PRIVACY_MODE_OPT_OUT = "opt-out"
MUPL_PRIVACY_MODES = [MUPL_PRIVACY_MODE_OPT_IN, MUPL_PRIVACY_MODE_OPT_OUT]

DEFAULT_MUPL_ENABLED = False
DEFAULT_MUPL_PRIVACY_MODE = MUPL_PRIVACY_MODE_OPT_IN
DEFAULT_MUPL_MIN_INTERACTIONS = 5
DEFAULT_MUPL_RETENTION_DAYS = 90

# Preference learning constants
PREF_SMOOTHING_ALPHA = 0.3
PREF_MIN_INTERACTIONS = 5
PREF_RETENTION_DAYS = 90

# Neural System Configuration
CONF_NEURON_CONTEXT_ENTITIES = "neuron_context_entities"
CONF_NEURON_STATE_ENTITIES = "neuron_state_entities"
CONF_NEURON_MOOD_ENTITIES = "neuron_mood_entities"
CONF_NEURON_ENABLED = "neuron_enabled"
CONF_NEURON_EVALUATION_INTERVAL = "neuron_evaluation_interval"

# Default neuron config
DEFAULT_NEURON_ENABLED = True
DEFAULT_NEURON_EVALUATION_INTERVAL = 60  # seconds
DEFAULT_NEURON_CONTEXT_ENTITIES: list[str] = []
DEFAULT_NEURON_STATE_ENTITIES: list[str] = []
DEFAULT_NEURON_MOOD_ENTITIES: list[str] = []

# Neuron types for UI
NEURON_TYPE_CONTEXT = "context"
NEURON_TYPE_STATE = "state"
NEURON_TYPE_MOOD = "mood"
NEURON_TYPES = [NEURON_TYPE_CONTEXT, NEURON_TYPE_STATE, NEURON_TYPE_MOOD]

# Calendar Context Neuron
CONF_CALENDAR_CONTEXT_ENABLED = "calendar_context_enabled"
CONF_CALENDAR_ENTITIES = "calendar_entities"
CONF_CALENDAR_LOOKAHEAD_HOURS = "calendar_lookahead_hours"
CONF_CALENDAR_MEETING_SOON_MINUTES = "calendar_meeting_soon_minutes"

DEFAULT_CALENDAR_CONTEXT_ENABLED = False
DEFAULT_CALENDAR_ENTITIES: list[str] = []
DEFAULT_CALENDAR_LOOKAHEAD_HOURS = 24
DEFAULT_CALENDAR_MEETING_SOON_MINUTES = 30

# Entity profile (controls sensor/card breadth)
CONF_ENTITY_PROFILE = "entity_profile"
ENTITY_PROFILE_CORE = "core"
ENTITY_PROFILE_FULL = "full"
ENTITY_PROFILES = [ENTITY_PROFILE_CORE, ENTITY_PROFILE_FULL]
DEFAULT_ENTITY_PROFILE = ENTITY_PROFILE_CORE

# Suggestion Panel
CONF_SUGGESTION_PANEL_ENABLED = "suggestion_panel_enabled"
CONF_SUGGESTION_MAX_PENDING = "suggestion_max_pending"
CONF_SUGGESTION_MAX_HISTORY = "suggestion_max_history"
CONF_SUGGESTION_EXPIRY_HOURS = "suggestion_expiry_hours"

DEFAULT_SUGGESTION_PANEL_ENABLED = True
DEFAULT_SUGGESTION_MAX_PENDING = 50
DEFAULT_SUGGESTION_MAX_HISTORY = 200
DEFAULT_SUGGESTION_EXPIRY_HOURS = 72

# Mood Dashboard
CONF_MOOD_DASHBOARD_ENABLED = "mood_dashboard_enabled"
CONF_MOOD_HISTORY_MAX_ENTRIES = "mood_history_max_entries"

DEFAULT_MOOD_DASHBOARD_ENABLED = True
DEFAULT_MOOD_HISTORY_MAX_ENTRIES = 100

# Knowledge Graph Sync
CONF_KNOWLEDGE_GRAPH_ENABLED = "knowledge_graph_enabled"
CONF_KNOWLEDGE_GRAPH_SYNC_INTERVAL = "knowledge_graph_sync_interval"

DEFAULT_KNOWLEDGE_GRAPH_ENABLED = True
DEFAULT_KNOWLEDGE_GRAPH_SYNC_INTERVAL = 3600  # 1 hour

# ML Context Module
CONF_ML_ENABLED = "ml_enabled"
CONF_ML_ENTITIES = "ml_entities"
CONF_ML_ANOMALY_CONTAMINATION = "ml_anomaly_contamination"
CONF_ML_HABIT_WINDOW_SIZE = "ml_habit_window_size"

DEFAULT_ML_ENABLED = False
DEFAULT_ML_ENTITIES: list[str] = []
DEFAULT_ML_ANOMALY_CONTAMINATION = 0.1
DEFAULT_ML_HABIT_WINDOW_SIZE = 100

# Waste Collection Reminder Module
CONF_WASTE_ENABLED = "waste_enabled"
CONF_WASTE_ENTITIES = "waste_entities"
CONF_WASTE_TTS_ENABLED = "waste_tts_enabled"
CONF_WASTE_TTS_ENTITY = "waste_tts_entity"
CONF_WASTE_REMINDER_EVENING_HOUR = "waste_reminder_evening_hour"
CONF_WASTE_REMINDER_MORNING_HOUR = "waste_reminder_morning_hour"

DEFAULT_WASTE_ENABLED = False
DEFAULT_WASTE_ENTITIES: list[str] = []
DEFAULT_WASTE_TTS_ENABLED = True
DEFAULT_WASTE_TTS_ENTITY = ""
DEFAULT_WASTE_REMINDER_EVENING_HOUR = 19
DEFAULT_WASTE_REMINDER_MORNING_HOUR = 7

# Birthday Reminder Module
CONF_BIRTHDAY_ENABLED = "birthday_enabled"
CONF_BIRTHDAY_CALENDAR_ENTITIES = "birthday_calendar_entities"
CONF_BIRTHDAY_LOOKAHEAD_DAYS = "birthday_lookahead_days"
CONF_BIRTHDAY_TTS_ENABLED = "birthday_tts_enabled"
CONF_BIRTHDAY_TTS_ENTITY = "birthday_tts_entity"
CONF_BIRTHDAY_REMINDER_HOUR = "birthday_reminder_hour"

DEFAULT_BIRTHDAY_ENABLED = False
DEFAULT_BIRTHDAY_CALENDAR_ENTITIES: list[str] = []
DEFAULT_BIRTHDAY_LOOKAHEAD_DAYS = 14
DEFAULT_BIRTHDAY_TTS_ENABLED = True
DEFAULT_BIRTHDAY_TTS_ENTITY = ""
DEFAULT_BIRTHDAY_REMINDER_HOUR = 8

# Entity Tags (v3.2.2)
ENTITY_TAGS_STORE_KEY = "ai_home_copilot.entity_tags"
ENTITY_TAGS_STORE_VERSION = 1

# ---------------------------------------------------------------------------
# Zone Automation Engine (v10.0.0)
# ---------------------------------------------------------------------------
CONF_ZONE_AUTOMATION_ENABLED = "zone_automation_enabled"
CONF_ZONE_AUTOMATION_EVAL_INTERVAL = "zone_automation_eval_interval"
CONF_ZONE_AUTOMATION_PRESENCE_TIMEOUT = "zone_automation_presence_timeout"
CONF_ZONE_AUTOMATION_LIGHT_MODE = "zone_automation_light_mode"
CONF_ZONE_AUTOMATION_TARGET_LUX = "zone_automation_target_lux"
CONF_ZONE_AUTOMATION_OUTDOOR_SENSOR = "zone_automation_outdoor_sensor"
CONF_ZONE_AUTOMATION_CIRCADIAN_ENABLED = "zone_automation_circadian_enabled"
CONF_ZONE_AUTOMATION_MEDIA_FOLLOW = "zone_automation_media_follow"
CONF_ZONE_AUTOMATION_AUTO_TAG = "zone_automation_auto_tag"

DEFAULT_ZONE_AUTOMATION_ENABLED = True
DEFAULT_ZONE_AUTOMATION_EVAL_INTERVAL = 30  # seconds
DEFAULT_ZONE_AUTOMATION_PRESENCE_TIMEOUT = 300  # 5 min grace period
DEFAULT_ZONE_AUTOMATION_LIGHT_MODE = "auto"  # auto | manual | circadian | presence_only
DEFAULT_ZONE_AUTOMATION_TARGET_LUX = 300.0
DEFAULT_ZONE_AUTOMATION_OUTDOOR_SENSOR = ""
DEFAULT_ZONE_AUTOMATION_CIRCADIAN_ENABLED = True
DEFAULT_ZONE_AUTOMATION_MEDIA_FOLLOW = True
DEFAULT_ZONE_AUTOMATION_AUTO_TAG = True

LIGHT_MODE_AUTO = "auto"
LIGHT_MODE_MANUAL = "manual"
LIGHT_MODE_CIRCADIAN = "circadian"
LIGHT_MODE_PRESENCE_ONLY = "presence_only"
LIGHT_MODES = [LIGHT_MODE_AUTO, LIGHT_MODE_MANUAL, LIGHT_MODE_CIRCADIAN, LIGHT_MODE_PRESENCE_ONLY]

# Domain → (tag_id, tag_name, color, icon) mapping for entity auto-tagging
DOMAIN_TAG_MAP: dict[str, tuple[str, str, str, str]] = {
    "light": ("licht", "Licht", "#fbbf24", "mdi:lightbulb"),
    "binary_sensor": ("bewegung", "Bewegung", "#f87171", "mdi:motion-sensor"),
    "sensor": ("sensor", "Sensor", "#60a5fa", "mdi:thermometer"),
    "media_player": ("media", "Media", "#a78bfa", "mdi:speaker"),
    "climate": ("klima", "Klima", "#34d399", "mdi:thermostat"),
    "cover": ("beschattung", "Beschattung", "#fb923c", "mdi:window-shutter"),
    "switch": ("schalter", "Schalter", "#6366f1", "mdi:toggle-switch"),
    "fan": ("lueftung", "Lüftung", "#22d3ee", "mdi:fan"),
    "camera": ("kamera", "Kamera", "#f472b6", "mdi:cctv"),
    "device_tracker": ("tracker", "Tracker", "#fb923c", "mdi:crosshairs-gps"),
    "person": ("person", "Person", "#a78bfa", "mdi:account"),
}

# Entity role classification (used by zone auto-assignment)
ENTITY_ROLE_MAP: dict[str, str] = {
    "light": "lights",
    "binary_sensor": "presence",  # motion/presence sensors
    "sensor": "brightness",       # lux sensors get brightness role
    "media_player": "media",
    "climate": "climate",
    "cover": "covers",
    "switch": "switches",
    "fan": "fans",
    "camera": "cameras",
    "device_tracker": "presence",
    "person": "presence",
}

# ---------------------------------------------------------------------------
# Centralized Defaults Map (v9.6.0)
# ---------------------------------------------------------------------------
# Single source of truth for ALL configuration defaults.
# Used by ZeroConfig, Options Flow, and merged_entry_config to ensure
# every key always has a safe, documented default value.

DEFAULTS_MAP: dict[str, object] = {
    # Connection
    CONF_HOST: DEFAULT_HOST,
    CONF_PORT: DEFAULT_PORT,
    CONF_TOKEN: "",
    CONF_TEST_LIGHT: DEFAULT_TEST_LIGHT,
    CONF_WEBHOOK_ID: "",
    CONF_WEBHOOK_URL: "",
    # Entity Profile
    CONF_ENTITY_PROFILE: DEFAULT_ENTITY_PROFILE,
    # Watchdog
    CONF_WATCHDOG_ENABLED: DEFAULT_WATCHDOG_ENABLED,
    CONF_WATCHDOG_INTERVAL_SECONDS: DEFAULT_WATCHDOG_INTERVAL_SECONDS,
    CONF_ENABLE_USER_PREFERENCES: DEFAULT_ENABLE_USER_PREFERENCES,
    # Media Context
    CONF_MEDIA_MUSIC_PLAYERS: DEFAULT_MEDIA_MUSIC_PLAYERS,
    CONF_MEDIA_TV_PLAYERS: DEFAULT_MEDIA_TV_PLAYERS,
    CONF_MEDIA_CONTEXT_V2_ENABLED: False,
    # Devlog Push
    CONF_DEVLOG_PUSH_ENABLED: DEFAULT_DEVLOG_PUSH_ENABLED,
    CONF_DEVLOG_PUSH_INTERVAL_SECONDS: DEFAULT_DEVLOG_PUSH_INTERVAL_SECONDS,
    CONF_DEVLOG_PUSH_PATH: DEFAULT_DEVLOG_PUSH_PATH,
    CONF_DEVLOG_PUSH_MAX_LINES: DEFAULT_DEVLOG_PUSH_MAX_LINES,
    CONF_DEVLOG_PUSH_MAX_CHARS: DEFAULT_DEVLOG_PUSH_MAX_CHARS,
    # Events Forwarder
    CONF_EVENTS_FORWARDER_ENABLED: DEFAULT_EVENTS_FORWARDER_ENABLED,
    CONF_EVENTS_FORWARDER_FLUSH_INTERVAL_SECONDS: DEFAULT_EVENTS_FORWARDER_FLUSH_INTERVAL_SECONDS,
    CONF_EVENTS_FORWARDER_MAX_BATCH: DEFAULT_EVENTS_FORWARDER_MAX_BATCH,
    CONF_EVENTS_FORWARDER_FORWARD_CALL_SERVICE: DEFAULT_EVENTS_FORWARDER_FORWARD_CALL_SERVICE,
    CONF_EVENTS_FORWARDER_IDEMPOTENCY_TTL_SECONDS: DEFAULT_EVENTS_FORWARDER_IDEMPOTENCY_TTL_SECONDS,
    CONF_EVENTS_FORWARDER_PERSISTENT_QUEUE_ENABLED: DEFAULT_EVENTS_FORWARDER_PERSISTENT_QUEUE_ENABLED,
    CONF_EVENTS_FORWARDER_PERSISTENT_QUEUE_MAX_SIZE: DEFAULT_EVENTS_FORWARDER_PERSISTENT_QUEUE_MAX_SIZE,
    CONF_EVENTS_FORWARDER_PERSISTENT_QUEUE_FLUSH_INTERVAL_SECONDS: DEFAULT_EVENTS_FORWARDER_PERSISTENT_QUEUE_FLUSH_INTERVAL_SECONDS,
    CONF_EVENTS_FORWARDER_INCLUDE_HABITUS_ZONES: DEFAULT_EVENTS_FORWARDER_INCLUDE_HABITUS_ZONES,
    CONF_EVENTS_FORWARDER_INCLUDE_MEDIA_PLAYERS: DEFAULT_EVENTS_FORWARDER_INCLUDE_MEDIA_PLAYERS,
    CONF_EVENTS_FORWARDER_ADDITIONAL_ENTITIES: DEFAULT_EVENTS_FORWARDER_ADDITIONAL_ENTITIES,
    # HA Errors Digest
    CONF_HA_ERRORS_DIGEST_ENABLED: DEFAULT_HA_ERRORS_DIGEST_ENABLED,
    CONF_HA_ERRORS_DIGEST_INTERVAL_SECONDS: DEFAULT_HA_ERRORS_DIGEST_INTERVAL_SECONDS,
    CONF_HA_ERRORS_DIGEST_MAX_LINES: DEFAULT_HA_ERRORS_DIGEST_MAX_LINES,
    # Debug
    CONF_DEBUG_LEVEL: DEFAULT_DEBUG_LEVEL,
    # PilotSuite UX
    CONF_PILOTSUITE_SHOW_SAFETY_BACKUP_BUTTONS: DEFAULT_PILOTSUITE_SHOW_SAFETY_BACKUP_BUTTONS,
    CONF_PILOTSUITE_SHOW_DEV_SURFACE_BUTTONS: DEFAULT_PILOTSUITE_SHOW_DEV_SURFACE_BUTTONS,
    CONF_PILOTSUITE_SHOW_GRAPH_BRIDGE_BUTTONS: DEFAULT_PILOTSUITE_SHOW_GRAPH_BRIDGE_BUTTONS,
    # Suggestion Seed
    CONF_SUGGESTION_SEED_ENTITIES: DEFAULT_SUGGESTION_SEED_ENTITIES,
    CONF_SEED_ALLOWED_DOMAINS: DEFAULT_SEED_ALLOWED_DOMAINS,
    CONF_SEED_BLOCKED_DOMAINS: DEFAULT_SEED_BLOCKED_DOMAINS,
    CONF_SEED_MAX_OFFERS_PER_HOUR: DEFAULT_SEED_MAX_OFFERS_PER_HOUR,
    CONF_SEED_MIN_SECONDS_BETWEEN_OFFERS: DEFAULT_SEED_MIN_SECONDS_BETWEEN_OFFERS,
    CONF_SEED_MAX_OFFERS_PER_UPDATE: DEFAULT_SEED_MAX_OFFERS_PER_UPDATE,
    # Ollama
    CONF_OLLAMA_HOST: DEFAULT_OLLAMA_HOST,
    CONF_OLLAMA_PORT: DEFAULT_OLLAMA_PORT,
    # SearXNG
    CONF_SEARXNG_ENABLED: DEFAULT_SEARXNG_ENABLED,
    CONF_SEARXNG_HOST: DEFAULT_SEARXNG_HOST,
    CONF_SEARXNG_PORT: DEFAULT_SEARXNG_PORT,
    # User Preferences
    CONF_USER_PREFERENCE_ENABLED: DEFAULT_USER_PREFERENCE_ENABLED,
    CONF_TRACKED_USERS: DEFAULT_TRACKED_USERS,
    CONF_PRIMARY_USER: DEFAULT_PRIMARY_USER,
    CONF_USER_LEARNING_MODE: DEFAULT_USER_LEARNING_MODE,
    # MUPL
    CONF_MUPL_ENABLED: DEFAULT_MUPL_ENABLED,
    CONF_MUPL_PRIVACY_MODE: DEFAULT_MUPL_PRIVACY_MODE,
    CONF_MUPL_MIN_INTERACTIONS: DEFAULT_MUPL_MIN_INTERACTIONS,
    CONF_MUPL_RETENTION_DAYS: DEFAULT_MUPL_RETENTION_DAYS,
    # Neural System
    CONF_NEURON_ENABLED: DEFAULT_NEURON_ENABLED,
    CONF_NEURON_EVALUATION_INTERVAL: DEFAULT_NEURON_EVALUATION_INTERVAL,
    CONF_NEURON_CONTEXT_ENTITIES: DEFAULT_NEURON_CONTEXT_ENTITIES,
    CONF_NEURON_STATE_ENTITIES: DEFAULT_NEURON_STATE_ENTITIES,
    CONF_NEURON_MOOD_ENTITIES: DEFAULT_NEURON_MOOD_ENTITIES,
    # Calendar
    CONF_CALENDAR_CONTEXT_ENABLED: DEFAULT_CALENDAR_CONTEXT_ENABLED,
    CONF_CALENDAR_ENTITIES: DEFAULT_CALENDAR_ENTITIES,
    CONF_CALENDAR_LOOKAHEAD_HOURS: DEFAULT_CALENDAR_LOOKAHEAD_HOURS,
    CONF_CALENDAR_MEETING_SOON_MINUTES: DEFAULT_CALENDAR_MEETING_SOON_MINUTES,
    # Suggestion Panel
    CONF_SUGGESTION_PANEL_ENABLED: DEFAULT_SUGGESTION_PANEL_ENABLED,
    CONF_SUGGESTION_MAX_PENDING: DEFAULT_SUGGESTION_MAX_PENDING,
    CONF_SUGGESTION_MAX_HISTORY: DEFAULT_SUGGESTION_MAX_HISTORY,
    CONF_SUGGESTION_EXPIRY_HOURS: DEFAULT_SUGGESTION_EXPIRY_HOURS,
    # Mood Dashboard
    CONF_MOOD_DASHBOARD_ENABLED: DEFAULT_MOOD_DASHBOARD_ENABLED,
    CONF_MOOD_HISTORY_MAX_ENTRIES: DEFAULT_MOOD_HISTORY_MAX_ENTRIES,
    # Knowledge Graph
    CONF_KNOWLEDGE_GRAPH_ENABLED: DEFAULT_KNOWLEDGE_GRAPH_ENABLED,
    CONF_KNOWLEDGE_GRAPH_SYNC_INTERVAL: DEFAULT_KNOWLEDGE_GRAPH_SYNC_INTERVAL,
    # ML
    CONF_ML_ENABLED: DEFAULT_ML_ENABLED,
    CONF_ML_ENTITIES: DEFAULT_ML_ENTITIES,
    CONF_ML_ANOMALY_CONTAMINATION: DEFAULT_ML_ANOMALY_CONTAMINATION,
    CONF_ML_HABIT_WINDOW_SIZE: DEFAULT_ML_HABIT_WINDOW_SIZE,
    # Waste
    CONF_WASTE_ENABLED: DEFAULT_WASTE_ENABLED,
    CONF_WASTE_ENTITIES: DEFAULT_WASTE_ENTITIES,
    CONF_WASTE_TTS_ENABLED: DEFAULT_WASTE_TTS_ENABLED,
    CONF_WASTE_TTS_ENTITY: DEFAULT_WASTE_TTS_ENTITY,
    CONF_WASTE_REMINDER_EVENING_HOUR: DEFAULT_WASTE_REMINDER_EVENING_HOUR,
    CONF_WASTE_REMINDER_MORNING_HOUR: DEFAULT_WASTE_REMINDER_MORNING_HOUR,
    # Birthday
    CONF_BIRTHDAY_ENABLED: DEFAULT_BIRTHDAY_ENABLED,
    CONF_BIRTHDAY_CALENDAR_ENTITIES: DEFAULT_BIRTHDAY_CALENDAR_ENTITIES,
    CONF_BIRTHDAY_LOOKAHEAD_DAYS: DEFAULT_BIRTHDAY_LOOKAHEAD_DAYS,
    CONF_BIRTHDAY_TTS_ENABLED: DEFAULT_BIRTHDAY_TTS_ENABLED,
    CONF_BIRTHDAY_TTS_ENTITY: DEFAULT_BIRTHDAY_TTS_ENTITY,
    CONF_BIRTHDAY_REMINDER_HOUR: DEFAULT_BIRTHDAY_REMINDER_HOUR,
    # Zone Automation
    CONF_ZONE_AUTOMATION_ENABLED: DEFAULT_ZONE_AUTOMATION_ENABLED,
    CONF_ZONE_AUTOMATION_EVAL_INTERVAL: DEFAULT_ZONE_AUTOMATION_EVAL_INTERVAL,
    CONF_ZONE_AUTOMATION_PRESENCE_TIMEOUT: DEFAULT_ZONE_AUTOMATION_PRESENCE_TIMEOUT,
    CONF_ZONE_AUTOMATION_LIGHT_MODE: DEFAULT_ZONE_AUTOMATION_LIGHT_MODE,
    CONF_ZONE_AUTOMATION_TARGET_LUX: DEFAULT_ZONE_AUTOMATION_TARGET_LUX,
    CONF_ZONE_AUTOMATION_OUTDOOR_SENSOR: DEFAULT_ZONE_AUTOMATION_OUTDOOR_SENSOR,
    CONF_ZONE_AUTOMATION_CIRCADIAN_ENABLED: DEFAULT_ZONE_AUTOMATION_CIRCADIAN_ENABLED,
    CONF_ZONE_AUTOMATION_MEDIA_FOLLOW: DEFAULT_ZONE_AUTOMATION_MEDIA_FOLLOW,
    CONF_ZONE_AUTOMATION_AUTO_TAG: DEFAULT_ZONE_AUTOMATION_AUTO_TAG,
}


def ensure_defaults(config: dict) -> dict:
    """Return a copy of *config* with all missing keys filled from DEFAULTS_MAP.

    This guarantees that every configurable option has a defined value,
    regardless of whether the user went through ZeroConfig, QuickStart, or
    Manual Setup.  List defaults are shallow-copied to avoid mutation.
    """
    result = dict(config)
    for key, default in DEFAULTS_MAP.items():
        if key not in result:
            result[key] = list(default) if isinstance(default, list) else default
    return result
