from __future__ import annotations

import logging
from pathlib import Path
import shutil

from homeassistant.components import persistent_notification
from homeassistant.core import HomeAssistant
from homeassistant.util import dt as dt_util

from .habitus_dashboard_store import HabitusDashboardState, async_get_state, async_set_state
from .habitus_zones_store import async_get_zones

_LOGGER = logging.getLogger(__name__)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)


def _lovelace_yaml_for_zone(zone_id: str, zone_name: str, entity_ids: list[str]) -> str:
    """Return a YAML snippet for one Lovelace view.

    Keep it simple and robust: one entities card + one history graph.
    """

    entities_yaml = "\n".join(f"          - entity: {eid}" for eid in entity_ids)
    if not entities_yaml:
        entities_yaml = "          - entity: sensor.time\n            name: (no entities configured)"

    graph_ents = entity_ids[:12]
    graph_yaml = "\n".join(f"          - {eid}" for eid in graph_ents)
    if not graph_yaml:
        graph_yaml = "          - sensor.time"

    return (
        f"  - title: {zone_name}\n"
        f"    path: hz-{zone_id}\n"
        f"    icon: mdi:home-circle\n"
        f"    cards:\n"
        f"      - type: entities\n"
        f"        title: {zone_name} — Controls & Signals\n"
        f"        show_header_toggle: false\n"
        f"        entities:\n"
        f"{entities_yaml}\n\n"
        f"      - type: history-graph\n"
        f"        title: {zone_name} — History (last 24h)\n"
        f"        hours_to_show: 24\n"
        f"        entities:\n"
        f"{graph_yaml}\n"
    )


async def async_generate_habitus_zones_dashboard(hass: HomeAssistant, entry_id: str) -> Path:
    zones = await async_get_zones(hass, entry_id)

    now = dt_util.now()
    ts = now.strftime("%Y%m%d_%H%M%S")

    views = []
    for z in zones:
        views.append(_lovelace_yaml_for_zone(z.zone_id, z.name, list(z.entity_ids)))

    content = (
        "# Generated by AI Home CoPilot (Habitus zones)\n"
        "# Import this as a YAML dashboard or copy views into an existing dashboard.\n\n"
        "title: Habitus Zones\n"
        "views:\n"
        + ("\n".join(views) if views else "  - title: Habitus Zones\n    path: habitus-zones\n    icon: mdi:layers-outline\n    cards: []\n")
    )

    out_dir = Path(hass.config.path("ai_home_copilot"))
    out_path = out_dir / f"habitus_zones_dashboard_{ts}.yaml"

    await hass.async_add_executor_job(_write_text, out_path, content)

    st = await async_get_state(hass)
    st.last_path = str(out_path)
    await async_set_state(hass, st)

    persistent_notification.async_create(
        hass,
        f"Generated Habitus zones dashboard YAML at: {out_path}",
        title="AI Home CoPilot Habitus dashboard",
        notification_id="ai_home_copilot_habitus_dashboard",
    )

    _LOGGER.info("Generated Habitus zones dashboard at %s", out_path)
    return out_path


async def async_publish_last_habitus_dashboard(hass: HomeAssistant) -> str:
    st = await async_get_state(hass)

    if not st.last_path:
        # Nothing generated yet.
        raise FileNotFoundError("No Habitus dashboard generated yet")

    src = Path(st.last_path)
    if not src.exists():
        raise FileNotFoundError(str(src))

    www_dir = Path(hass.config.path("www")) / "ai_home_copilot"
    dst = www_dir / src.name

    await hass.async_add_executor_job(_copy, src, dst)

    st.last_published_path = str(dst)
    await async_set_state(hass, st)

    url = f"/local/ai_home_copilot/{dst.name}"
    persistent_notification.async_create(
        hass,
        f"Habitus dashboard published. Open: {url}",
        title="AI Home CoPilot Habitus dashboard download",
        notification_id="ai_home_copilot_habitus_dashboard_download",
    )

    _LOGGER.info("Published Habitus dashboard to %s (url=%s)", dst, url)
    return url
