from __future__ import annotations

import logging
from pathlib import Path
import shutil

from homeassistant.components import persistent_notification
from homeassistant.core import HomeAssistant
from homeassistant.util import dt as dt_util

from .habitus_dashboard_store import HabitusDashboardState, async_get_state, async_set_state
from .habitus_zones_store import async_get_zones

_LOGGER = logging.getLogger(__name__)


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)


def _domain(entity_id: str) -> str:
    return entity_id.split(".", 1)[0] if "." in entity_id else ""


def _entities_card_yaml(title: str, entities: list[str]) -> str:
    lines = [
        "      - type: entities",
        f"        title: {title}",
        "        show_header_toggle: false",
        "        entities:",
    ]
    if not entities:
        lines.append("          - type: section")
        lines.append("            label: (none)")
    else:
        for eid in entities:
            lines.append(f"          - entity: {eid}")
    return "\n".join(lines)


def _history_graph_yaml(title: str, entities: list[str]) -> str:
    lines = [
        "      - type: history-graph",
        f"        title: {title}",
        "        hours_to_show: 24",
        "        entities:",
    ]
    if not entities:
        lines.append("          - sensor.time")
    else:
        for eid in entities[:12]:
            lines.append(f"          - {eid}")
    return "\n".join(lines)


def _logbook_yaml(title: str, entities: list[str]) -> str:
    lines = [
        "      - type: logbook",
        f"        title: {title}",
        "        hours_to_show: 24",
        "        entities:",
    ]
    if not entities:
        lines.append("          - sensor.time")
    else:
        for eid in entities[:12]:
            lines.append(f"          - {eid}")
    return "\n".join(lines)


def _lovelace_yaml_for_zone(zone_id: str, zone_name: str, entity_ids: list[str]) -> str:
    """Return a YAML snippet for one Lovelace view.

    UX goal: small, readable grouping by domain (no custom cards).
    """

    groups: dict[str, list[str]] = {
        "binary_sensor": [],
        "light": [],
        "cover": [],
        "climate": [],
        "media_player": [],
        "sensor": [],
        "other": [],
    }

    for eid in entity_ids:
        d = _domain(eid)
        if d in groups:
            groups[d].append(eid)
        else:
            groups["other"].append(eid)

    # Key signals for history/logbook: motion + lights + media + climate.
    key_signals = (
        groups["binary_sensor"][:2]
        + groups["light"][:6]
        + groups["media_player"][:4]
        + groups["climate"][:2]
    )

    cards: list[str] = []
    cards.append(_entities_card_yaml(f"{zone_name} — Lights", groups["light"]))
    cards.append(_entities_card_yaml(f"{zone_name} — Presence/Motion", groups["binary_sensor"]))
    if groups["media_player"]:
        cards.append(_entities_card_yaml(f"{zone_name} — Media", groups["media_player"]))
    if groups["climate"]:
        cards.append(_entities_card_yaml(f"{zone_name} — Climate", groups["climate"]))
    if groups["cover"]:
        cards.append(_entities_card_yaml(f"{zone_name} — Covers", groups["cover"]))
    if groups["sensor"]:
        cards.append(_entities_card_yaml(f"{zone_name} — Sensors", groups["sensor"]))
    if groups["other"]:
        cards.append(_entities_card_yaml(f"{zone_name} — Other", groups["other"]))

    cards.append(_history_graph_yaml(f"{zone_name} — History (24h)", key_signals))
    cards.append(_logbook_yaml(f"{zone_name} — Logbook (24h)", key_signals))

    return (
        f"  - title: {zone_name}\n"
        f"    path: hz-{zone_id}\n"
        f"    icon: mdi:home-circle\n"
        f"    cards:\n"
        + "\n\n".join(cards)
        + "\n"
    )


async def async_generate_habitus_zones_dashboard(hass: HomeAssistant, entry_id: str) -> Path:
    zones = await async_get_zones(hass, entry_id)

    now = dt_util.now()
    ts = now.strftime("%Y%m%d_%H%M%S")

    views = []
    for z in zones:
        views.append(_lovelace_yaml_for_zone(z.zone_id, z.name, list(z.entity_ids)))

    content = (
        "# Generated by AI Home CoPilot (Habitus zones)\n"
        "# Import this as a YAML dashboard or copy views into an existing dashboard.\n\n"
        "title: Habitus Zones\n"
        "views:\n"
        + ("\n".join(views) if views else "  - title: Habitus Zones\n    path: habitus-zones\n    icon: mdi:layers-outline\n    cards: []\n")
    )

    out_dir = Path(hass.config.path("ai_home_copilot"))
    out_path = out_dir / f"habitus_zones_dashboard_{ts}.yaml"
    latest_path = out_dir / "habitus_zones_dashboard_latest.yaml"

    await hass.async_add_executor_job(_write_text, out_path, content)
    await hass.async_add_executor_job(_write_text, latest_path, content)

    st = await async_get_state(hass)
    st.last_path = str(out_path)
    await async_set_state(hass, st)

    persistent_notification.async_create(
        hass,
        (
            f"Generated Habitus zones dashboard YAML at:\n{out_path}\n\n"
            f"Latest (stable):\n{latest_path}"
        ),
        title="AI Home CoPilot Habitus dashboard",
        notification_id="ai_home_copilot_habitus_dashboard",
    )

    _LOGGER.info("Generated Habitus zones dashboard at %s", out_path)
    return out_path


async def async_publish_last_habitus_dashboard(hass: HomeAssistant) -> str:
    st = await async_get_state(hass)

    if not st.last_path:
        # Nothing generated yet.
        raise FileNotFoundError("No Habitus dashboard generated yet")

    # Publish stable latest file, and keep timestamped archive locally.
    out_dir = Path(hass.config.path("ai_home_copilot"))
    latest_src = out_dir / "habitus_zones_dashboard_latest.yaml"
    if latest_src.exists():
        src = latest_src
    else:
        src = Path(st.last_path)

    if not src.exists():
        raise FileNotFoundError(str(src))

    www_dir = Path(hass.config.path("www")) / "ai_home_copilot"
    dst = www_dir / "habitus_zones_dashboard_latest.yaml"

    await hass.async_add_executor_job(_copy, src, dst)

    st.last_published_path = str(dst)
    await async_set_state(hass, st)

    url = f"/local/ai_home_copilot/{dst.name}"
    persistent_notification.async_create(
        hass,
        f"Habitus dashboard published (stable). Open: {url}",
        title="AI Home CoPilot Habitus dashboard download",
        notification_id="ai_home_copilot_habitus_dashboard_download",
    )

    _LOGGER.info("Published Habitus dashboard to %s (url=%s)", dst, url)
    return url
